---

- hosts: "primary,replicas"
  become: yes
  become_user: root
  gather_facts: true
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'
    - '../inventory/group_vars/all.yml'

  tasks:

  - name: "Ensure MariaDB RPMs directory exists"
    file:
      path: "{{ mariadb_rpms_path }}"
      state: directory
      mode: '0755'

  - name: "Check if MariaDB RPMs directory exists"
    stat:
      path: "{{ mariadb_rpms_path }}"
    register: rpm_dir

  - name: "Fail if MariaDB RPMs directory does not exist"
    fail:
      msg: "The directory {{ mariadb_rpms_path }} does not exist."
    when: not rpm_dir.stat.exists

  - name: "Debug cs_package_manager_custom_version"
    debug:
      var: cs_package_manager_custom_version
    when: cs_package_manager_custom_version is defined and cs_package_manager_custom_version != "" and cs_package_manager_custom_version is not none

  - name: "Download cs_package_manager script"
    get_url:
      url: "https://raw.githubusercontent.com/mariadb-corporation/mariadb-columnstore-engine/refs/heads/fix/cs-package-manager-rocky-install/cmapi/scripts/cs_package_manager.sh"
      dest: "{{ mariadb_rpms_path }}/cs_package_manager.sh"
      mode: '0755'
    when: cs_package_manager_custom_version is defined and cs_package_manager_custom_version != "" and cs_package_manager_custom_version is not none

- hosts: "primary,replicas"
  become: yes
  become_user: root
  gather_facts: true
  vars_files:
    - '../inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'
    - '../inventory/group_vars/all.yml'

  tasks:

  - name: "Install MariaDB packages using cs_package_manager script"
    command: >-
      bash {{ mariadb_rpms_path }}/cs_package_manager.sh install {{ cs_package_manager_custom_version }}
      --with-dev
    register: cs_package_manager_output
    when: cs_package_manager_custom_version is defined and cs_package_manager_custom_version != "" and cs_package_manager_custom_version is not none

  - name: "cs_package_manager output"
    debug:
      msg: "{{ cs_package_manager_output.stdout }}"
    when: cs_package_manager_custom_version is defined and cs_package_manager_custom_version != "" and cs_package_manager_custom_version is not none and cs_package_manager_output is defined

  - name: "cs_package_manager errors"
    debug:
      msg: "{{ cs_package_manager_output.stderr }}"
    when: cs_package_manager_custom_version is defined and cs_package_manager_custom_version != "" and cs_package_manager_custom_version is not none and cs_package_manager_output is defined and cs_package_manager_output.stderr != ""
